### ISSUE TITLE
프로그래머스 모의고사 3회 (~8/23)

### ISSUE THREAD

**Issue by ycs1m1yk** [ycs1m1yk/TWS#2]
https://career.programmers.co.kr/competitions/2627/2022-%EC%8B%A4%EC%A0%84-%EB%8C%80%EB%B9%84-%EB%AA%A8%EC%9D%98%EA%B3%A0%EC%82%AC

- [x] 1차
- [x] 2차
- [x] 3차

**Comment by SeolJaeHyeok** [comment]
오 감사합니다잉:)

주말에 하나씩 풀어보는건가요?

**Comment by ycs1m1yk** [comment]
> 오 감사합니다잉:)
> 
> 주말에 하나씩 풀어보는건가요?

넵 8/23까지 응시가능하니

8월 1~3째주 주말에 풀면 좋겠네요!
