### ISSUE TITLE
2022/08/01

### ISSUE THREAD

**Issue by SeolJaeHyeok** [ycs1m1yk/TWS#3]
어떤 알고리즘 유형을 푸는 게 좋을까 생각하다가 우선 완전 탐색부터 푸는 게 나을 것 같아서 임의로 5문제 추가해봤습니다!

추가하거나 교체하고 싶으시면 교체하고 푸쉬해주세요:)

**Comment by ycs1m1yk** [comment]
ㅋㅋㅋㅋㅋ 5문제 확인요
